# https://wpengine.com/resources/containers-clusters-wordpress/
# https://www.youtube.com/watch?v=P_iqK_7qiZw&ab_channel=WPGains

version: '3.7'
services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    image: inception_mariadb:42
    init: true
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    image: inception_wordpress:42
    init: true
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - DOMAIN_NAME
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html
    restart: always

  nginx:
    build: requirements/nginx/
    container_name: nginx
    image: inception_nginx:42
    init: true
    environment:
      - DOMAIN_NAME
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ~/data/mariadb

  wordpress:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress
